### ISSUE TITLE
masterとdevブランチを分ける

### ISSUE THREAD

**Issue by hoshimi** [hoshimi/motocal#4]
これまで、開発用サイトも http://hsimyu.net/motocal/ 以下に置いて、
[dev.html](http://hsimyu.net/motocal/dev.html)にアクセスすることで開発版のテストを行っていたが、

- 本番リリース時にもコミットが出来てしまうのは悲しい
- dev.html に追加した内容をindex.htmlに追加し忘れることがある

ので、きちんとブランチを分け、開発版の運用を見直す。

**Comment by gin0606** [comment]
他の人の pull-request を受け入れるなら開発用ブランチを master にして、本番用は production みたいな感じだと分かりやすいと思います💡

**Comment by hoshimi** [comment]
なるほど、了解です。
